In [76]:
import pandas as pd

In [77]:
#читаем наш файл
df = pd.read_csv(
    r'C:\Users\Maria\OneDrive\Desktop\Анализ_убыточности_типографии\Данные\CSV_из_excel_в_csv\1c_90_2024.csv',
    sep=';',
    encoding='utf-8'
)

df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,: Виды деят. : Полиграфическая : Ставка НДС :...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,за 2024 г.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"ООО ""Капитал Принт""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Дата,Документ,Операции,Дебет,NaN,Кредит,NaN,Текущее сальдо,NaN
5,NaN,NaN,NaN,Счет,Сумма,Счет,Сумма,NaN,NaN
6,Сальдо на 01.01.24,NaN,NaN,NaN,,NaN,,NaN,NaN
7,03.01.24,Накладная ШЖ1827905,Продажа (счет 90)/ Евроторг Учтена выручка\nЕв...,62.1,,90.01,"503,82",,
8,03.01.24,Накладная ЭЕ0138062,Продажа (счет 90)/ Корс Сити ООО Учтена выручк...,62.1,,90.01,"620,16",,
9,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,

In [78]:
#выводим названия колонок
print(df.columns.tolist())

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']

In [79]:
#смотрим, как это выглядит
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,: Виды деят. : Полиграфическая : Ставка НДС :...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,за 2024 г.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"ООО ""Капитал Принт""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Дата,Документ,Операции,Дебет,NaN,Кредит,NaN,Текущее сальдо,NaN
5,NaN,NaN,NaN,Счет,Сумма,Счет,Сумма,NaN,NaN
6,Сальдо на 01.01.24,NaN,NaN,NaN,,NaN,,NaN,NaN
7,03.01.24,Накладная ШЖ1827905,Продажа (счет 90)/ Евроторг Учтена выручка\nЕв...,62.1,,90.01,"503,82",,
8,03.01.24,Накладная ЭЕ0138062,Продажа (счет 90)/ Корс Сити ООО Учтена выручк...,62.1,,90.01,"620,16",,
9,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,
10,04.01.24,Накладная ШЖ1827906,Продажа (счет 90)/ Академическая книга Учтена ...,62.1,,90.01,"1 422,00",,
11,04.01.24,Накладная ЭЕ0138064,Продажа (счет 90)/ Авангард-торг Учтена выручк...,62.1,,90.01,"38,40",,
12,04.01.24,Накладная ШЖ1827907,Продажа (счет 90)/ Кинг тут ООО Учтена выручка...,62.1,,90.01,"1 426,32",,
13,04.01.24,Накладная ШЖ1827908,Продажа (счет 90)/ Апулья ООО Учтена выручка\n...,62.1,,90.01,"201,26",,
14,04.01.24,Накладная ШЖ1827909,Продажа (счет 90)/ Плэй хард Учтена выручка\nП...,62.1,,90.01,"6 000,00",,

In [80]:
#смотрим, сколько колонок и строк
print(df.columns.tolist())
df.shape

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']

(1522, 9)

In [81]:
#оставляем только нужные колонки
df.iloc[:8]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,: Виды деят. : Полиграфическая : Ставка НДС :...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,за 2024 г.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"ООО ""Капитал Принт""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Дата,Документ,Операции,Дебет,NaN,Кредит,NaN,Текущее сальдо,NaN
5,NaN,NaN,NaN,Счет,Сумма,Счет,Сумма,NaN,NaN
6,Сальдо на 01.01.24,NaN,NaN,NaN,,NaN,,NaN,NaN
7,03.01.24,Накладная ШЖ1827905,Продажа (счет 90)/ Евроторг Учтена выручка\nЕв...,62.1,,90.01,"503,82",,

In [82]:
#берем первую строку как названия столбцов
df.columns = df.iloc[0]
#удаляем лишние строки
df = df[7:]
#сбрасываем индексы
df = df.reset_index(drop=True)
#смотрим, что получилось
df.head()

,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,03.01.24,Накладная ШЖ1827905,Продажа (счет 90)/ Евроторг Учтена выручка\nЕв...,62.1,,90.01,"503,82",,
1,03.01.24,Накладная ЭЕ0138062,Продажа (счет 90)/ Корс Сити ООО Учтена выручк...,62.1,,90.01,"620,16",,
2,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,
3,04.01.24,Накладная ШЖ1827906,Продажа (счет 90)/ Академическая книга Учтена ...,62.1,,90.01,"1 422,00",,
4,04.01.24,Накладная ЭЕ0138064,Продажа (счет 90)/ Авангард-торг Учтена выручк...,62.1,,90.01,"38,40",,

In [83]:
#смотрим, сколько колонок и строк
print(df.columns.tolist())
df.shape

['Карточка счета: 90.01', nan, nan, nan, nan, nan, nan, nan, nan]

(1515, 9)

In [84]:
#сбрасываем индексы
df = df.iloc[2:].reset_index(drop=True)
df.head()

,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,
1,04.01.24,Накладная ШЖ1827906,Продажа (счет 90)/ Академическая книга Учтена ...,62.1,,90.01,"1 422,00",,
2,04.01.24,Накладная ЭЕ0138064,Продажа (счет 90)/ Авангард-торг Учтена выручк...,62.1,,90.01,"38,40",,
3,04.01.24,Накладная ШЖ1827907,Продажа (счет 90)/ Кинг тут ООО Учтена выручка...,62.1,,90.01,"1 426,32",,
4,04.01.24,Накладная ШЖ1827908,Продажа (счет 90)/ Апулья ООО Учтена выручка\n...,62.1,,90.01,"201,26",,

In [85]:
#смотрим кол-во колонок и строк
df.shape

(1513, 9)

In [86]:
#смотрим параметры нашего DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Карточка счета: 90.01  1512 non-null   str
 1   nan                    1510 non-null   str
 2   nan                    1510 non-null   str
 3   nan                    1510 non-null   str
 4   nan                    1512 non-null   str
 5   nan                    1510 non-null   str
 6   nan                    1512 non-null   str
 7   nan                    1510 non-null   str
 8   nan                    1510 non-null   str
dtypes: str(9)
memory usage: 106.5 KB

In [87]:
#выводим номера колонок
for i, col in enumerate(df.columns):
    print(i, col)

0 Карточка счета: 90.01
1 nan
2 nan
3 nan
4 nan
5 nan
6 nan
7 nan
8 nan

In [88]:
df.head()

,Карточка счета: 90.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,
1,04.01.24,Накладная ШЖ1827906,Продажа (счет 90)/ Академическая книга Учтена ...,62.1,,90.01,"1 422,00",,
2,04.01.24,Накладная ЭЕ0138064,Продажа (счет 90)/ Авангард-торг Учтена выручк...,62.1,,90.01,"38,40",,
3,04.01.24,Накладная ШЖ1827907,Продажа (счет 90)/ Кинг тут ООО Учтена выручка...,62.1,,90.01,"1 426,32",,
4,04.01.24,Накладная ШЖ1827908,Продажа (счет 90)/ Апулья ООО Учтена выручка\n...,62.1,,90.01,"201,26",,

In [89]:
#присваиваем названия нашим колонкам
df.columns = [
    'Дата',
    'Документ',
    'Операции',
    'Счет_дебет',
    'Сумма_дебет',
    'Счет_кредит',
    'Сумма_кредит',
    'Текущее_сальдо',
    'Сальдо'
]

df.head()

,Дата,Документ,Операции,Счет_дебет,Сумма_дебет,Счет_кредит,Сумма_кредит,Текущее_сальдо,Сальдо
0,03.01.24,Акт вып. работ (реализ) с табл. частью 0000000...,"Акт вып.работ (реализ), табл, покупатель: ИСТ ...",62.1,,90.01,"90,90",,
1,04.01.24,Накладная ШЖ1827906,Продажа (счет 90)/ Академическая книга Учтена ...,62.1,,90.01,"1 422,00",,
2,04.01.24,Накладная ЭЕ0138064,Продажа (счет 90)/ Авангард-торг Учтена выручк...,62.1,,90.01,"38,40",,
3,04.01.24,Накладная ШЖ1827907,Продажа (счет 90)/ Кинг тут ООО Учтена выручка...,62.1,,90.01,"1 426,32",,
4,04.01.24,Накладная ШЖ1827908,Продажа (счет 90)/ Апулья ООО Учтена выручка\n...,62.1,,90.01,"201,26",,

In [90]:
#для анализа нужна колонка Сумма_кредит. Смотрим тип колонки
df['Сумма_кредит'].head()

0       90,90
1    1 422,00
2       38,40
3    1 426,32
4      201,26
Name: Сумма_кредит, dtype: str

In [91]:
#переводим str в float64
cols = ['Сумма_дебет', 'Сумма_кредит', 'Текущее_сальдо', 'Сальдо']
for col in cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(' ', '', regex=False)
        .str.replace(',', '.', regex=False)
    )

df[cols] = df[cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Дата            1512 non-null   str
 1   Документ        1510 non-null   str
 2   Операции        1510 non-null   str
 3   Счет_дебет      1510 non-null   str
 4   Сумма_дебет     0 non-null      float64
 5   Счет_кредит     1510 non-null   str
 6   Сумма_кредит    1511 non-null   float64
 7   Текущее_сальдо  0 non-null      float64
 8   Сальдо          0 non-null      float64
dtypes: float64(4), str(5)
memory usage: 106.5 KB

In [93]:
#теперь можем посчитать все статистические показатели
df['Сумма_кредит'].describe()

count    1.511000e+03
mean     2.486226e+03
std      4.834913e+04
min     -4.320000e+02
25%      1.622400e+02
50%      5.670000e+02
75%      1.352400e+03
max      1.878906e+06
Name: Сумма_кредит, dtype: float64

In [94]:
#выводим медиану
df['Сумма_кредит'].median()

np.float64(567.0)

In [95]:
#зная то, что при выгрузке ОСВ с 1с бухгалтерии, есть итогая строка, которая будет выбросом, обрезаем ее
df.tail(5)

,Дата,Документ,Операции,Счет_дебет,Сумма_дебет,Счет_кредит,Сумма_кредит,Текущее_сальдо,Сальдо
1508,30.12.24,Накладная ЭЕ0138444,Продажа (счет 90)/ РОЯЛОАК Учтена выручка\nРОЯ...,62.1,NaN,90.01,104.02,NaN,NaN
1509,30.12.24,Накладная УХ0227774,Продажа (счет 90)/ Ажур Групп Учтена выручка\n...,62.1,NaN,90.01,7450.32,NaN,NaN
1510,Обороты за период,NaN,NaN,NaN,NaN,NaN,1878905.91,NaN,NaN
1511,Сальдо на 31.12.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
#обрезаем
df = df.iloc[:-3]
df.tail(5)

,Дата,Документ,Операции,Счет_дебет,Сумма_дебет,Счет_кредит,Сумма_кредит,Текущее_сальдо,Сальдо
1505,30.12.24,Накладная УХ0227771,Продажа (счет 90)/ Представительство ТАСК Учте...,62.1,NaN,90.01,367.20,NaN,NaN
1506,30.12.24,Накладная УХ0227772,Продажа (счет 90)/ Лаймарис ООО Учтена выручка...,62.1,NaN,90.01,567.00,NaN,NaN
1507,30.12.24,Накладная ЭЕ0138443,Продажа (счет 90)/ Корс Сити ООО Учтена выручк...,62.1,NaN,90.01,356.72,NaN,NaN
1508,30.12.24,Накладная ЭЕ0138444,Продажа (счет 90)/ РОЯЛОАК Учтена выручка\nРОЯ...,62.1,NaN,90.01,104.02,NaN,NaN
1509,30.12.24,Накладная УХ0227774,Продажа (счет 90)/ Ажур Групп Учтена выручка\n...,62.1,NaN,90.01,7450.32,NaN,NaN

In [97]:
#заново считаем показатели, они будут отличаться
df['Сумма_кредит'].describe()

count     1510.000000
mean      1243.564192
std       2083.744931
min       -432.000000
25%        162.240000
50%        567.000000
75%       1348.650000
max      26697.240000
Name: Сумма_кредит, dtype: float64